---
title: "simulation_new"
author: "Jieqi Tu"
date: "11/2/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(PoisBinOrd)
```

```{r correlation selection function}
create_corr = function(n.P,n.B,n.O ,lambda.vec, prop.vec, prop.list){
  CorrLimit = correlation.limits(n.P,n.B,n.O,lambda.vec,prop.vec,prop.list)
  to.upper = function(X) X[lower.tri(X,diag=TRUE)]
  to.lower = function(X) X[upper.tri(X,diag=TRUE)]
  upper  = as.vector(na.omit(to.upper(t(CorrLimit))))
  lower = as.vector(na.omit(to.lower(t(CorrLimit))))
  
  corr = list()
  for (i in 1:length(upper)){
    corr[[i]] = runif(n = 1, min = lower[i], max = upper[i])}
  
  M = unlist(corr)
  N = diag(n.P + n.B + n.O)  
  N[lower.tri(N)] = M 
  corr.mat = N+t(N)   
  diag(corr.mat) = 1   
  corr.mat
  
  return(  list(  CorrLimit = CorrLimit, 
                  final_corr = data.frame(lower=lower, final_corr=unlist(corr), upper=upper),
                  corr.mat = corr.mat
                 ))
}

create_corr(n.P = 2,n.B = 2,n.O = 2 ,lambda.vec = c(2,7),prop.vec = c(0.8,0.9),prop.list = list(c(0.65,0.8,0.9),c(0.5,0.8,0.95)))
```

```{r create very weak correlation matrix SIGMA}
# very weak correlation
set.seed(5)
W_Corr = runif(n=15, min = 0.001,max = 0.199)
W_PN_Indicator = sample(c(-1,1), size = 15, replace = TRUE)
W_Corr_Final = W_Corr*W_PN_Indicator
W_Corr_Final

# Create overall correlation matrix, SIGMA
M = W_Corr_Final
N = diag(6)  
N[lower.tri(N)] = M  # lower triangle 
corr.mat_W = N+t(N)    # symmetric matrix
diag(corr.mat_W) = 1   
corr.mat_W

# Validates the specified correlation matrix
validation.corr(n.P,n.B,n.O,corr.vec=NULL,corr.mat_W)

# checks if there are range violations among pp, po, pb, bb, bo, oo combinations
correlation.bound.check(n.P,n.B,n.O,lambda.vec,prop.vec,prop.list, corr.vec=NULL,corr.mat_W)
```

```{r create parameter for scenario 1 and 2}
# small marginal poisson rates, even marginal binary and orinal
n.P = 2 # Number of Poisson variables
n.B = 2 # Number of binary variables
n.O = 2 # Number of ordinal variables
lambda.vec = c(0.2, 0.7)# Rate vector for Poisson variables
prop.vec=c(0.55, 0.45)                               # Probability vector for binary variables
prop.list=list(c(0.25, 0.5, 0.75), c(0.20, 0.45, 0.75))  # A list of probability vectors for ordinal variables. (cdf-cutoff)

para1 = list(n.P, n.O, n.B, lambda.vec = lambda.vec, prop.vec = prop.vec, prop.list = prop.list, corr.mat = corr.mat_W)
```

```{r create function to calculate CI for rho}
# Create function to calculate CI for rhos
CI_high_cal_rho = function(r, N) {
  CU = 0.5*log((1+r)/(1-r)) + 1.96*sqrt(1/N)
  CI_high = (exp(2*CU)-1)/(exp(2*CU)+1)
  return(CI_high)
}
CI_low_cal_rho = function(r, N) {
  CL = 0.5*log((1+r)/(1-r)) - 1.96*sqrt(1/N)
  CI_low = (exp(2*CL)-1)/(exp(2*CL)+1)
  return(CI_low)
}


```

```{r create simulation function}
# Computes the final intermediate correlation matrix, SIGMA*
final.corr.mat = overall.corr.mat(n.P, n.B, n.O, lambda.vec, prop.vec, prop.list, corr.vec=NULL, corr.mat_W)
para1$final.corr.mat  = final.corr.mat

simulation.function = function(para, samplesize, n.sim) {
    mymixdata = list(); para_esti=list(); para_true = list(); para_LCI = list(); para_UCI = list()
    
    # Computes the final intermediate correlation matrix, SIGMA*
    final.corr.mat = overall.corr.mat(para[[1]], para[[2]], para[[3]], para$lambda.vec,para1$prop.vec,para$prop.list, corr.vec=NULL, para$corr.mat)
    para$final.corr.mat  = final.corr.mat
 
  for (i in 1:n.sim) {
    # Generate mixed data
    mymixdata[[i]] = gen.PoisBinOrd(n = samplesize, n.P = para[[1]], n.B = para[[2]], n.O = para[[3]],
                               lambda.vec = para$lambda.vec, prop.vec = para$prop.vec, prop.list = para$prop.list, 
                               final.corr.mat = para$final.corr.mat)
    # Poisson
    para_poi     = apply(mymixdata[[i]], MARGIN = 2, mean)[1:2] # Poisson Mean = Poisson Variance
    para_poi_LCI = (-1.96*sqrt(1/(4*samplesize)) + sqrt(para_poi))^2
    para_poi_UCI = (1.96*sqrt(1/(4*samplesize)) + sqrt(para_poi))^2
    
    # Binary
    para_bin     = apply(mymixdata[[i]], MARGIN = 2, mean)[3:4]
    para_bin_LCI = para_bin - 1.96*sqrt(para_bin*(1-para_bin) / samplesize)
    para_bin_UCI = para_bin + 1.96*sqrt(para_bin*(1-para_bin) / samplesize)
    
    # Ordinal
    para_ordi = c(  cumsum( table(mymixdata[[i]][,5]))[1:3], cumsum( table(mymixdata[[i]][,6]))[1:3]  ) / samplesize # cumu proportion
    para_ordi_prop0 = c(   table(mymixdata[[i]][,5])[1], table(mymixdata[[i]][,6])[1]  ) / samplesize
    para_ordi_prop1 = c(   table(mymixdata[[i]][,5])[2], table(mymixdata[[i]][,6])[2]  ) / samplesize
    para_ordi_prop2 = c(   table(mymixdata[[i]][,5])[3], table(mymixdata[[i]][,6])[3]  ) / samplesize
    para_ordi_prop3 = c(   table(mymixdata[[i]][,5])[4], table(mymixdata[[i]][,6])[4]  ) / samplesize
    
    para_ordi_LCI1 = para_ordi[c(1,4)] - 1.96*sqrt(  para_ordi_prop0*(1-para_ordi_prop0)  /samplesize )
    para_ordi_LCI2 = para_ordi[c(2,5)] - 
                     1.96*sqrt(  (  para_ordi_prop0*(1-para_ordi_prop0) + para_ordi_prop1*(1-para_ordi_prop1) - 2*para_ordi_prop0*para_ordi_prop1  ) /samplesize )
    para_ordi_LCI3 = para_ordi[c(3,6)] - 
                     1.96*sqrt(  (     para_ordi_prop0*(1-para_ordi_prop0) +   para_ordi_prop1*(1-para_ordi_prop1) +   para_ordi_prop2*(1-para_ordi_prop2) 
                                   - 2*para_ordi_prop0*para_ordi_prop1     - 2*para_ordi_prop0*para_ordi_prop2     - 2*para_ordi_prop1*para_ordi_prop2) /samplesize )
    
    
    para_ordi_UCI1 = para_ordi[c(1,4)] + 1.96*sqrt(  para_ordi_prop0*(1-para_ordi_prop0)  /samplesize )
    para_ordi_UCI2 = para_ordi[c(2,5)] + 
                     1.96*sqrt(  (  para_ordi_prop0*(1-para_ordi_prop0) + para_ordi_prop1*(1-para_ordi_prop1) - 2*para_ordi_prop0*para_ordi_prop1  ) /samplesize )
    para_ordi_UCI3 = para_ordi[c(3,6)] + 
                     1.96*sqrt(  (     para_ordi_prop0*(1-para_ordi_prop0) +   para_ordi_prop1*(1-para_ordi_prop1) +   para_ordi_prop2*(1-para_ordi_prop2) 
                                   - 2*para_ordi_prop0*para_ordi_prop1     - 2*para_ordi_prop0*para_ordi_prop2     - 2*para_ordi_prop1*para_ordi_prop2) /samplesize )
    # Correlation
    corr = cor(mymixdata[[i]])
    to.upper = function(X) X[lower.tri(X,diag=TRUE)]
    corr_f = to.upper(corr)[c(2:6, 8:11, 13:15, 17:18, 20)]
    
    
    # Output
    para_esti[[i]] = as.vector(c(para_poi,para_bin,  para_ordi, corr_f))
    para_true[[i]] = c(para$lambda.vec, para$prop.vec, unlist(para$prop.list),  to.upper(para$corr.mat)[c(2:6, 8:11, 13:15, 17:18, 20)])
    para_LCI[[i]] = c(para_poi_LCI, para_bin_LCI, para_ordi_LCI1, para_ordi_LCI2, para_ordi_LCI3,  CI_low_cal_rho(corr_f , samplesize) )
    para_UCI[[i]] = c(para_poi_UCI, para_bin_UCI, para_ordi_UCI1, para_ordi_UCI2, para_ordi_UCI3, CI_high_cal_rho(corr_f , samplesize) )
  }

# Point Estimation
  Para_True = matrix( unlist(para_true), nrow=n.sim, byrow=TRUE)
  Para_Esti = matrix( unlist(para_esti), nrow=n.sim, byrow=TRUE)
  theta_true = apply( Para_True, MARGIN =2, mean)
  theta_esti_mean = apply( Para_Esti, MARGIN =2, mean)
  theta_esti_sd = apply( Para_Esti, MARGIN =2, sd)

# Accuracy and Precision 
  RB = (  (theta_esti_mean - theta_true)/theta_true        )*100
  SB = (  abs(theta_esti_mean - theta_true)/theta_esti_sd  )*100
  RMSE = sqrt(   apply( (Para_Esti - Para_True)^2, MARGIN =2, mean )   )
  
# Confidence Interval 
  LCI = matrix( unlist(para_LCI), nrow=n.sim, byrow=TRUE)
  UCI = matrix( unlist(para_UCI), nrow=n.sim, byrow=TRUE)
  para_true_forCI = c(para$lambda.vec, para$prop.vec, unlist(para$prop.list)[c(1,4,2,5,3,6)], to.upper(para$corr.mat)[c(2:6, 8:11, 13:15, 17:18, 20)])
  Para_True_forCI = matrix(rep(para_true_forCI,n.sim), nrow=n.sim, byrow=TRUE)
  
  CR = apply(  ifelse( ( Para_True_forCI - LCI >= 0) & (UCI - Para_True_forCI >= 0),1,0 )   ,  MARGIN =2, sum)  / n.sim
  CR = CR[c(1:4, 5,8, 6,9, 7,10, 11:25)]

  inference = data.frame(Para_True      = round(theta_true,4),
              Para_Esti_Mean = round(theta_esti_mean,4), 
              Para_Esti_SD   = round(theta_esti_sd,4),
              RB             = round(RB,4),            
              SB             = round(SB,4), 
              RMSE           = round(RMSE,4),
              CR             = round(CR, 4))
  rownames(inference) = c("lambda1", "lambda2", "p1", "p2", "t11", "t21", "t31", "t12", "t22", "t32",
                          "rho12", "rho13", "rho14", "rho15", "rho16", "rho23", "rho24", "rho25", "rho26",
                          "rho34", "rho35", "rho36", "rho45", "rho46", "rho56")
  
  
  return(inference)
}

simulation.function(para1, 100, 1000)
```

