---
title: "simulation"
author: "Jieqi Tu"
date: "10/30/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(PoisBinOrd)
```

```{r create true parameters even}
# small marginal poisson rates, even marginal binary and orinal
n.P = 2 # Number of Poisson variables
n.B = 2 # Number of binary variables
n.O = 2 # Number of ordinal variables
lambda.vec = c(0.2, 0.7)# Rate vector for Poisson variables
prop.vec=c(0.55, 0.45)                               # Probability vector for binary variables
prop.list=list(c(0.25, 0.5, 0.75), c(0.20, 0.45, 0.75))  # A list of probability vectors for ordinal variables. (cdf-cutoff)
```

```{r create weak correlations}
# very weak correlation
set.seed(5)
W_Corr = runif(n=15, min = 0.001,max = 0.199)
W_PN_Indicator = sample(c(-1,1), size = 15, replace = TRUE)
W_Corr_Final = W_Corr*W_PN_Indicator
W_Corr_Final

# Create overall correlation matrix, SIGMA
M = W_Corr_Final
N = diag(6)  
N[lower.tri(N)] = M  # lower triangle 
corr.mat_W = N+t(N)    # symmetric matrix
diag(corr.mat_W) = 1   
corr.mat_W

# Validates the specified correlation matrix
validation.corr(n.P,n.B,n.O,corr.vec=NULL,corr.mat_W)

# checks if there are range violations among pp, po, pb, bb, bo, oo combinations
correlation.bound.check(n.P,n.B,n.O,lambda.vec,prop.vec,prop.list, corr.vec=NULL,corr.mat_W)
```

```{r create strong correlation}
# weak correlation
set.seed(5)
M_Corr = runif(n=15, min = 0.2,max = 0.399)
M_PN_Indicator = sample(c(-1,1), size = 15, replace = TRUE)
M_Corr_Final = M_Corr*M_PN_Indicator
M_Corr_Final

# Create overall correlation matrix, SIGMA
M = M_Corr_Final
N = diag(6)  
N[lower.tri(N)] = M  # lower triangle 
corr.mat_M = N+t(N)    # symmetric matrix
diag(corr.mat_M) = 1   
corr.mat_M

# Validates the specified correlation matrix
validation.corr(n.P,n.B,n.O,corr.vec=NULL,corr.mat_M)

correlation.limits(n.P,n.B,n.O,lambda.vec,prop.vec,prop.list)
# checks if there are range violations among pp, po, pb, bb, bo, oo combinations
correlation.bound.check(n.P,n.B,n.O,lambda.vec,prop.vec,prop.list, corr.vec=NULL,corr.mat_M)
```

```{r create parameter for small and even parameters}
# create parameter for very weak corr, small and even parameters
para1 = list(n.P, n.O, n.B, lambda.vec = lambda.vec, prop.vec = prop.vec, prop.list = prop.list, corr.mat = corr.mat_W)

# create parameter for weak corr, small and even parameters
para9 = list(n.P, n.O, n.B, lambda.vec = lambda.vec, prop.vec = prop.vec, prop.list = prop.list, corr.mat = corr.mat_M)
```

```{r create true parameters not even}
n.P = 2 # Number of Poisson variables
n.B = 2 # Number of binary variables
n.O = 2 # Number of ordinal variables
lambda.vec = c(0.2, 0.7)# Rate vector for Poisson variables
prop.vec=c(0.8, 0.9)                               # Probability vector for binary variables
prop.list=list(c(0.65, 0.8, 0.9), c(0.5, 0.8, 0.95))

# checks if there are range violations among pp, po, pb, bb, bo, oo combinations
correlation.bound.check(n.P,n.B,n.O,lambda.vec,prop.vec,prop.list, corr.vec=NULL,corr.mat_W)
# checks if there are range violations among pp, po, pb, bb, bo, oo combinations
correlation.bound.check(n.P,n.B,n.O,lambda.vec,prop.vec,prop.list, corr.vec=NULL,corr.mat_M)
```

```{r simulation}
# Create function to calculate CI for rhos
CI_high_cal_rho = function(r, N) {
  CU = 0.5*log((1+r)/(1-r)) + 1.96*sqrt(1/N)
  CI_high = (exp(2*CU)-1)/(exp(2*CU)+1)
  return(CI_high)
}
CI_low_cal_rho = function(r, N) {
  CL = 0.5*log((1+r)/(1-r)) - 1.96*sqrt(1/N)
  CI_low = (exp(2*CL)-1)/(exp(2*CL)+1)
  return(CI_low)
}



simulation.function = function(parameteters, N, n.sim = 1000) {

  # Create vectors to store estimates
  lambda1_s = numeric(n.sim); lambda1_ci_high = numeric(n.sim); lambda1_ci_low = numeric(n.sim)
  lambda2_s = numeric(n.sim); lambda2_ci_high = numeric(n.sim); lambda2_ci_low = numeric(n.sim)
  p1_s = numeric(n.sim); p1_ci_high = numeric(n.sim); p1_ci_low = numeric(n.sim)
  p2_s = numeric(n.sim); p2_ci_high = numeric(n.sim); p2_ci_low = numeric(n.sim)
  t11_s = numeric(n.sim); t11_ci_high = numeric(n.sim); t11_ci_low = numeric(n.sim)
  t21_s = numeric(n.sim); t21_ci_high = numeric(n.sim); t21_ci_low = numeric(n.sim)
  t31_s = numeric(n.sim); t31_ci_high = numeric(n.sim); t31_ci_low = numeric(n.sim)
  t12_s = numeric(n.sim); t12_ci_high = numeric(n.sim); t12_ci_low = numeric(n.sim)
  t22_s = numeric(n.sim); t22_ci_high = numeric(n.sim); t22_ci_low = numeric(n.sim)
  t32_s = numeric(n.sim); t32_ci_high = numeric(n.sim); t32_ci_low = numeric(n.sim)
  rho12_s = numeric(n.sim); rho12_ci_high = numeric(n.sim); rho12_ci_low = numeric(n.sim)
  rho13_s = numeric(n.sim); rho13_ci_high = numeric(n.sim); rho13_ci_low = numeric(n.sim)
  rho14_s = numeric(n.sim); rho14_ci_high = numeric(n.sim); rho14_ci_low = numeric(n.sim)
  rho15_s = numeric(n.sim); rho15_ci_high = numeric(n.sim); rho15_ci_low = numeric(n.sim)
  rho16_s = numeric(n.sim); rho16_ci_high = numeric(n.sim); rho16_ci_low = numeric(n.sim)
  rho23_s = numeric(n.sim); rho23_ci_high = numeric(n.sim); rho23_ci_low = numeric(n.sim)
  rho24_s = numeric(n.sim); rho24_ci_high = numeric(n.sim); rho24_ci_low = numeric(n.sim)
  rho25_s = numeric(n.sim); rho25_ci_high = numeric(n.sim); rho25_ci_low = numeric(n.sim)
  rho26_s = numeric(n.sim); rho26_ci_high = numeric(n.sim); rho26_ci_low = numeric(n.sim)
  rho34_s = numeric(n.sim); rho34_ci_high = numeric(n.sim); rho34_ci_low = numeric(n.sim)
  rho35_s = numeric(n.sim); rho35_ci_high = numeric(n.sim); rho35_ci_low = numeric(n.sim)
  rho36_s = numeric(n.sim); rho36_ci_high = numeric(n.sim); rho36_ci_low = numeric(n.sim)
  rho45_s = numeric(n.sim); rho45_ci_high = numeric(n.sim); rho45_ci_low = numeric(n.sim)
  rho46_s = numeric(n.sim); rho46_ci_high = numeric(n.sim); rho46_ci_low = numeric(n.sim)
  rho56_s = numeric(n.sim); rho56_ci_high = numeric(n.sim); rho56_ci_low = numeric(n.sim)
  
  
  for (i in 1:n.sim) {
    
    # Computes the final intermediate correlation matrix, SIGMA*
    final.corr.mat=overall.corr.mat(n.P,n.B,n.O,
                                lambda.vec,
                                prop.vec, 
                                prop.list,
                                corr.vec=NULL,parameteters$corr.mat)

    # Generate mixed data
    mymixdata = gen.PoisBinOrd(N, n.P, n.B, n.O,
                           lambda.vec,
                           prop.vec,
                           prop.list, 
                           final.corr.mat)

    lambda1.mean = mean(mymixdata[,1]); lambda1_s[i] = lambda1.mean
    lambda2.mean = mean(mymixdata[,2]); lambda2_s[i] = lambda2.mean
    p1.mean = mean(mymixdata[,3]); p1_s[i] = p1.mean
    p2.mean = mean(mymixdata[,4]); p2_s[i] = p2.mean
    t11.mean = length(mymixdata[,5][mymixdata[,5] == 0])/N; t11_s[i] = t11.mean
    t21.mean = length(mymixdata[,5][mymixdata[,5] <= 1])/N; t21_s[i] = t21.mean
    t31.mean = length(mymixdata[,5][mymixdata[,5] <= 2])/N; t31_s[i] = t31.mean
    t12.mean = length(mymixdata[,6][mymixdata[,5] == 0])/N; t12_s[i] = t12.mean
    t22.mean = length(mymixdata[,6][mymixdata[,6] <= 1])/N; t22_s[i] = t22.mean
    t32.mean = length(mymixdata[,6][mymixdata[,6] <= 2])/N; t32_s[i] = t32.mean
    correlation = cor(mymixdata)
    rho12_s[i] = correlation[1,2]
    rho13_s[i] = correlation[1,3]
    rho14_s[i] = correlation[1,4]
    rho15_s[i] = correlation[1,5]
    rho16_s[i] = correlation[1,6]
    rho23_s[i] = correlation[2,3]
    rho24_s[i] = correlation[2,4]
    rho25_s[i] = correlation[2,5]
    rho26_s[i] = correlation[2,6]
    rho34_s[i] = correlation[3,4]
    rho35_s[i] = correlation[3,5]
    rho36_s[i] = correlation[3,6]
    rho45_s[i] = correlation[4,5]
    rho46_s[i] = correlation[4,6]
    rho56_s[i] = correlation[5,6]
    
    # Calculate confidence interval
    lambda1_ci_low[i] = lambda1.mean - 1.96*sqrt(lambda1.mean/N)
    lambda1_ci_high[i] = lambda1.mean + 1.96*sqrt(lambda1.mean/N)
    lambda2_ci_low[i] = lambda2.mean - 1.96*sqrt(lambda2.mean/N)
    lambda2_ci_high[i] = lambda2.mean + 1.96*sqrt(lambda2.mean/N)
    p1_ci_low[i] = p1.mean-1.96*sqrt(p1.mean*(1-p1.mean)/N)
    p1_ci_high[i] = p1.mean+1.96*sqrt(p1.mean*(1-p1.mean)/N)
    p2_ci_low[i] = p2.mean-1.96*sqrt(p2.mean*(1-p2.mean)/N)
    p2_ci_high[i] = p2.mean+1.96*sqrt(p2.mean*(1-p2.mean)/N)
    t11_ci_low[i] = t11.mean-1.96*sqrt(t11.mean*(1-t11.mean)/N)
    t11_ci_high[i] = t11.mean+1.96*sqrt(t11.mean*(1-t11.mean)/N)
    prop01 = t11.mean; prop11 = t21.mean-t11.mean; prop21 = t31.mean-t21.mean
    prop02 = t12.mean; prop12 = t22.mean-t12.mean; prop22 = t32.mean-t22.mean
    t21_ci_low[i] = t21.mean-1.96*sqrt((prop01*(1-prop01)+prop11*(1-prop11)-2*prop01*prop11)/N)
    t21_ci_high[i] = t21.mean+1.96*sqrt((prop01*(1-prop01)+prop11*(1-prop11)-2*prop01*prop11)/N)
    t31_ci_low[i] = t31.mean-1.96*sqrt((prop01*(1-prop01)+prop11*(1-prop11)+prop21*(1-prop21)-2*prop01*prop11-2*prop11*prop21-2*prop01*prop21)/N)
    t31_ci_high[i] = t31.mean+1.96*sqrt((prop01*(1-prop01)+prop11*(1-prop11)+prop21*(1-prop21)-2*prop01*prop11-2*prop11*prop21-2*prop01*prop21)/N)
    t12_ci_low[i] = t12.mean-1.96*sqrt(t12.mean*(1-t12.mean)/N)
    t12_ci_high[i] = t12.mean+1.96*sqrt(t12.mean*(1-t12.mean)/N)
    t22_ci_low[i] = t22.mean-1.96*sqrt((prop02*(1-prop02)+prop12*(1-prop12)-2*prop02*prop12)/N)
    t22_ci_high[i] = t22.mean+1.96*sqrt((prop02*(1-prop02)+prop12*(1-prop12)-2*prop02*prop12)/N)
    t32_ci_low[i] = t32.mean-1.96*sqrt((prop02*(1-prop02)+prop12*(1-prop12)+prop22*(1-prop22)-2*prop02*prop12-2*prop12*prop22-2*prop02*prop22)/N)
    t32_ci_high[i] = t32.mean+1.96*sqrt((prop02*(1-prop02)+prop12*(1-prop12)+prop22*(1-prop22)-2*prop02*prop12-2*prop12*prop22-2*prop02*prop22)/N)
    rho12_ci_high[i] = CI_high_cal_rho(correlation[1,2], N)
    rho12_ci_low[i] = CI_low_cal_rho(correlation[1,2], N)
    rho13_ci_high[i] = CI_high_cal_rho(correlation[1,3], N)
    rho13_ci_low[i] = CI_low_cal_rho(correlation[1,3], N)
    rho14_ci_high[i] = CI_high_cal_rho(correlation[1,4], N)
    rho14_ci_low[i] = CI_low_cal_rho(correlation[1,4], N)
    rho15_ci_high[i] = CI_high_cal_rho(correlation[1,5], N)
    rho15_ci_low[i] = CI_low_cal_rho(correlation[1,5], N)
    rho16_ci_high[i] = CI_high_cal_rho(correlation[1,6], N)
    rho16_ci_low[i] = CI_low_cal_rho(correlation[1,6], N)
    rho23_ci_high[i] = CI_high_cal_rho(correlation[2,3], N)
    rho23_ci_low[i] = CI_low_cal_rho(correlation[2,3], N)
    rho24_ci_high[i] = CI_high_cal_rho(correlation[2,4], N)
    rho24_ci_low[i] = CI_low_cal_rho(correlation[2,4], N)
    rho25_ci_high[i] = CI_high_cal_rho(correlation[2,5], N)
    rho25_ci_low[i] = CI_low_cal_rho(correlation[2,5], N)
    rho26_ci_high[i] = CI_high_cal_rho(correlation[2,6], N)
    rho26_ci_low[i] = CI_low_cal_rho(correlation[2,6], N)
    rho34_ci_high[i] = CI_high_cal_rho(correlation[3,4], N)
    rho34_ci_low[i] = CI_low_cal_rho(correlation[3,4], N)
    rho35_ci_high[i] = CI_high_cal_rho(correlation[3,5], N)
    rho35_ci_low[i] = CI_low_cal_rho(correlation[3,5], N)
    rho36_ci_high[i] = CI_high_cal_rho(correlation[3,6], N)
    rho36_ci_low[i] = CI_low_cal_rho(correlation[3,6], N)
    rho45_ci_high[i] = CI_high_cal_rho(correlation[4,5], N)
    rho45_ci_low[i] = CI_low_cal_rho(correlation[4,5], N)
    rho46_ci_high[i] = CI_high_cal_rho(correlation[4,6], N)
    rho46_ci_low[i] = CI_low_cal_rho(correlation[4,6], N)
    rho56_ci_high[i] = CI_high_cal_rho(correlation[5,6], N)
    rho56_ci_low[i] = CI_low_cal_rho(correlation[5,6], N)
  }
  
  lambda1_cover = as.numeric(parameteters$lambda.vec[1]<= lambda1_ci_high & parameteters$lambda.vec[1]>= lambda1_ci_low)
  lambda2_cover = as.numeric(parameteters$lambda.vec[2]<= lambda2_ci_high & parameteters$lambda.vec[2]>= lambda2_ci_low)
  p1_cover = as.numeric(parameteters$prop.vec[1]<= p1_ci_high & parameteters$prop.vec[1]>= p1_ci_low)
  p2_cover = as.numeric(parameteters$prop.vec[2]<= p2_ci_high & parameteters$prop.vec[2]>= p2_ci_low)
  t11_cover = as.numeric(unlist(parameteters$prop.list[1])[1] <= t11_ci_high & unlist(parameteters$prop.list[1])[1] >= t11_ci_low)
  t21_cover = as.numeric(unlist(parameteters$prop.list[1])[2] <= t21_ci_high & unlist(parameteters$prop.list[1])[2] >= t21_ci_low)
  t31_cover = as.numeric(unlist(parameteters$prop.list[1])[3] <= t31_ci_high & unlist(parameteters$prop.list[1])[3] >= t31_ci_low)
  t12_cover = as.numeric(unlist(parameteters$prop.list[2])[1] <= t12_ci_high & unlist(parameteters$prop.list[2])[1] >= t12_ci_low)
  t22_cover = as.numeric(unlist(parameteters$prop.list[2])[2] <= t22_ci_high & unlist(parameteters$prop.list[2])[2] >= t22_ci_low)
  t32_cover = as.numeric(unlist(parameteters$prop.list[2])[3] <= t32_ci_high & unlist(parameteters$prop.list[2])[3] >= t32_ci_low)
  rho12_cover = as.numeric(parameteters$corr.mat[1,2] <= rho12_ci_high & parameteters$corr.mat[1,2] >= rho12_ci_low)
  rho13_cover = as.numeric(parameteters$corr.mat[1,3] <= rho13_ci_high & parameteters$corr.mat[1,3] >= rho13_ci_low)
  rho14_cover = as.numeric(parameteters$corr.mat[1,4] <= rho14_ci_high & parameteters$corr.mat[1,4] >= rho14_ci_low)
  rho15_cover = as.numeric(parameteters$corr.mat[1,5] <= rho15_ci_high & parameteters$corr.mat[1,5] >= rho15_ci_low)
  rho16_cover = as.numeric(parameteters$corr.mat[1,6] <= rho16_ci_high & parameteters$corr.mat[1,6] >= rho16_ci_low)
  rho23_cover = as.numeric(parameteters$corr.mat[2,3] <= rho23_ci_high & parameteters$corr.mat[2,3] >= rho23_ci_low)
  rho24_cover = as.numeric(parameteters$corr.mat[2,4] <= rho24_ci_high & parameteters$corr.mat[2,4] >= rho24_ci_low)
  rho25_cover = as.numeric(parameteters$corr.mat[2,5] <= rho25_ci_high & parameteters$corr.mat[2,5] >= rho25_ci_low)
  rho26_cover = as.numeric(parameteters$corr.mat[2,6] <= rho26_ci_high & parameteters$corr.mat[2,6] >= rho26_ci_low)
  rho34_cover = as.numeric(parameteters$corr.mat[3,4] <= rho34_ci_high & parameteters$corr.mat[3,4] >= rho34_ci_low)
  rho35_cover = as.numeric(parameteters$corr.mat[3,5] <= rho35_ci_high & parameteters$corr.mat[3,5] >= rho35_ci_low)
  rho36_cover = as.numeric(parameteters$corr.mat[3,6] <= rho36_ci_high & parameteters$corr.mat[3,6] >= rho36_ci_low)
  rho45_cover = as.numeric(parameteters$corr.mat[4,5] <= rho45_ci_high & parameteters$corr.mat[4,5] >= rho45_ci_low)
  rho46_cover = as.numeric(parameteters$corr.mat[4,6] <= rho12_ci_high & parameteters$corr.mat[4,6] >= rho46_ci_low)
  rho56_cover = as.numeric(parameteters$corr.mat[5,6] <= rho12_ci_high & parameteters$corr.mat[5,6] >= rho56_ci_low)
  result.matrix = cbind(lambda1_s, lambda1_ci_low, lambda1_ci_high, lambda1_cover,
                        lambda2_s, lambda2_ci_low, lambda2_ci_high, lambda2_cover,
                        p1_s, p1_ci_low, p1_ci_high, p1_cover, p2_s, p2_ci_low, p2_ci_high, p2_cover,
                        t11_s, t11_ci_low, t11_ci_high, t11_cover, t21_s, t21_ci_low, t21_ci_high, t21_cover, t31_s, t31_ci_low, t31_ci_high, t31_cover,
                        t12_s, t12_ci_low, t12_ci_high, t12_cover, t22_s, t22_ci_low, t22_ci_high, t22_cover, t32_s, t32_ci_low, t32_ci_high, t32_cover,
                        rho12_s, rho12_ci_low, rho12_ci_high, rho12_cover, rho13_s, rho13_ci_low, rho13_ci_high, rho13_cover,
                        rho14_s, rho14_ci_low, rho14_ci_high, rho14_cover, rho15_s, rho15_ci_low, rho15_ci_high, rho15_cover,
                        rho16_s, rho16_ci_low, rho16_ci_high, rho16_cover, rho23_s, rho23_ci_low, rho23_ci_high, rho16_cover,
                        rho24_s, rho24_ci_low, rho24_ci_high, rho24_cover, rho25_s, rho25_ci_low, rho25_ci_high, rho25_cover,
                        rho26_s, rho26_ci_low, rho26_ci_high, rho26_cover, rho34_s, rho34_ci_low, rho34_ci_high, rho34_cover,
                        rho35_s, rho35_ci_low, rho35_ci_high, rho35_cover, rho36_s, rho36_ci_low, rho36_ci_high, rho36_cover,
                        rho45_s, rho45_ci_low, rho45_ci_high, rho45_cover, rho46_s, rho46_ci_low, rho46_ci_high, rho46_cover,
                        rho56_s, rho56_ci_low, rho56_ci_high, rho56_cover) 
  
  # Calculate the coverage rate
  lambda1_CR = sum(lambda1_cover)/n.sim
  lambda2_CR = sum(lambda2_cover)/n.sim
  p1_CR = sum(p1_cover)/n.sim
  p2_CR = sum(p2_cover)/n.sim
  t11_CR = sum(t11_cover)/n.sim
  t21_CR = sum(t21_cover)/n.sim
  t31_CR = sum(t31_cover)/n.sim
  t12_CR = sum(t12_cover)/n.sim
  t22_CR = sum(t22_cover)/n.sim
  t32_CR = sum(t32_cover)/n.sim
  rho12_CR = sum(rho12_cover)/n.sim
  rho13_CR = sum(rho13_cover)/n.sim
  rho14_CR = sum(rho14_cover)/n.sim
  rho15_CR = sum(rho15_cover)/n.sim
  rho16_CR = sum(rho16_cover)/n.sim
  rho23_CR = sum(rho23_cover)/n.sim
  rho24_CR = sum(rho24_cover)/n.sim
  rho25_CR = sum(rho25_cover)/n.sim
  rho26_CR = sum(rho26_cover)/n.sim
  rho34_CR = sum(rho34_cover)/n.sim
  rho35_CR = sum(rho35_cover)/n.sim
  rho36_CR = sum(rho36_cover)/n.sim
  rho45_CR = sum(rho45_cover)/n.sim
  rho46_CR = sum(rho46_cover)/n.sim
  rho56_CR = sum(rho56_cover)/n.sim
  
  CR_result = list(lambda1 = lambda1_CR, lambda2 = lambda2_CR, p1 = p1_CR, p2 = p2_CR,
                   t11 = t11_CR, t21 = t21_CR, t31 = t31_CR,
                   t12 = t12_CR, t22 = t22_CR, t32 = t32_CR,
                   rho12 = rho12_CR, rho13 = rho13_CR, rho14 = rho14_CR, 
                   rho15 = rho15_CR, rho16 = rho16_CR, rho23 = rho23_CR,
                   rho24 = rho24_CR, rho25 = rho25_CR, rho26 = rho26_CR,
                   rho34 = rho34_CR, rho35 = rho35_CR, rho36 = rho36_CR,
                   rho45 = rho45_CR, rho46 = rho46_CR, rho56 = rho56_CR)
  
  lambda1_mean = mean(lambda1_s)
  lambda2_mean = mean(lambda2_s)
  p1_mean = mean(p1_s)
  p2_mean = mean(p2_s)
  t11_mean = mean(t11_s)
  t21_mean = mean(t21_s)
  t31_mean = mean(t31_s)
  t12_mean = mean(t12_s)
  t22_mean = mean(t22_s)
  t32_mean = mean(t32_s)
  rho12_mean = mean(rho12_s)
  rho13_mean = mean(rho13_s)
  rho14_mean = mean(rho14_s)
  rho15_mean = mean(rho15_s)
  rho16_mean = mean(rho16_s)
  rho23_mean = mean(rho23_s)
  rho24_mean = mean(rho24_s)
  rho25_mean = mean(rho25_s)
  rho26_mean = mean(rho26_s)
  rho34_mean = mean(rho34_s)
  rho35_mean = mean(rho35_s)
  rho36_mean = mean(rho36_s)
  rho45_mean = mean(rho45_s)
  rho46_mean = mean(rho46_s)
  rho56_mean = mean(rho56_s)
  
  mean_result = list(lambda1 = lambda1_mean, lambda2 = lambda2_mean, p1 = p1_mean, p2 = p2_mean,
                     t11 = t11_mean, t21 = t21_mean, t31 = t31_mean,
                     t12 = t12_mean, t22 = t22_mean, t32 = t32_mean,
                     rho12 = rho12_mean, rho13 = rho13_mean, rho14 = rho14_mean, 
                     rho15 = rho15_mean, rho16 = rho16_mean, rho23 = rho23_mean,
                     rho24 = rho24_mean, rho25 = rho25_mean, rho26 = rho26_mean,
                     rho34 = rho34_mean, rho35 = rho35_mean, rho36 = rho36_mean,
                     rho45 = rho45_mean, rho46 = rho46_mean, rho56 = rho56_mean)
  # Calculate RB
  lambda1_RB = ((lambda1_mean - parameteters$lambda.vec[1])/parameteters$lambda.vec[1])*100
  lambda2_RB = ((lambda2_mean - parameteters$lambda.vec[2])/parameteters$lambda.vec[2])*100
  p1_RB = ((p1_mean - parameteters$prop.vec[1])/parameteters$prop.vec[1])*100
  p2_RB = ((p2_mean - parameteters$prop.vec[2])/parameteters$prop.vec[2])*100
  t1_RB = ((c(t11_mean, t21_mean, t31_mean) - unlist(parameteters$prop.list[1]))/c(unlist(parameteters$prop.list[1])))*100
  t2_RB = ((c(t12_mean, t22_mean, t32_mean) - unlist(parameteters$prop.list[2]))/c(unlist(parameteters$prop.list[2])))*100
  rho12_RB = ((rho12_mean - parameteters$corr.mat[1,2])/parameteters$corr.mat[1,2])*100
  rho13_RB = ((rho13_mean - parameteters$corr.mat[1,3])/parameteters$corr.mat[1,3])*100
  rho14_RB = ((rho14_mean - parameteters$corr.mat[1,4])/parameteters$corr.mat[1,4])*100
  rho15_RB = ((rho15_mean - parameteters$corr.mat[1,5])/parameteters$corr.mat[1,5])*100
  rho16_RB = ((rho16_mean - parameteters$corr.mat[1,6])/parameteters$corr.mat[1,6])*100
  rho23_RB = ((rho23_mean - parameteters$corr.mat[2,3])/parameteters$corr.mat[2,3])*100
  rho24_RB = ((rho24_mean - parameteters$corr.mat[2,4])/parameteters$corr.mat[2,4])*100
  rho25_RB = ((rho25_mean - parameteters$corr.mat[2,5])/parameteters$corr.mat[2,5])*100
  rho26_RB = ((rho26_mean - parameteters$corr.mat[2,6])/parameteters$corr.mat[2,6])*100
  rho34_RB = ((rho34_mean - parameteters$corr.mat[3,4])/parameteters$corr.mat[3,4])*100
  rho35_RB = ((rho35_mean - parameteters$corr.mat[3,5])/parameteters$corr.mat[3,5])*100
  rho36_RB = ((rho36_mean - parameteters$corr.mat[3,6])/parameteters$corr.mat[3,6])*100
  rho45_RB = ((rho45_mean - parameteters$corr.mat[4,5])/parameteters$corr.mat[4,5])*100
  rho46_RB = ((rho46_mean - parameteters$corr.mat[4,6])/parameteters$corr.mat[4,6])*100
  rho56_RB = ((rho56_mean - parameteters$corr.mat[5,6])/parameteters$corr.mat[5,6])*100
  
  RB_result = list(lambda1 = lambda1_RB, lambda2 = lambda2_RB, p1 = p1_RB, p2 = p2_RB,
                   t1 = t1_RB, t2 = t2_RB,
                   rho12 = rho12_RB, rho13 = rho13_RB, rho14 = rho14_RB, 
                   rho15 = rho15_RB, rho16 = rho16_RB, rho23 = rho23_RB,
                   rho24 = rho24_RB, rho25 = rho25_RB, rho26 = rho26_RB,
                   rho34 = rho34_RB, rho35 = rho35_RB, rho36 = rho36_RB,
                   rho45 = rho45_RB, rho46 = rho46_RB, rho56 = rho56_RB)
  
  # Calculate SB
  lambda1_SB = (abs(lambda1_mean - parameteters$lambda.vec[1])/sd(lambda1_s))*100
  lambda2_SB = (abs(lambda2_mean - parameteters$lambda.vec[2])/sd(lambda2_s))*100
  p1_SB = (abs(p1_mean - parameteters$prop.vec[1])/sd(p1_s))*100
  p2_SB = (abs(p2_mean - parameteters$prop.vec[2])/sd(p2_s))*100
  t1_SB = (abs(c(t11_mean, t21_mean, t31_mean) - unlist(parameteters$prop.list[1]))/c(sd(t11_s), sd(t21_s), sd(t31_s)))*100
  t2_SB = (abs(c(t12_mean, t22_mean, t32_mean) - unlist(parameteters$prop.list[2]))/c(sd(t12_s), sd(t22_s), sd(t32_s)))*100
  rho12_SB = (abs(rho12_mean - parameteters$corr.mat[1,2])/sd(rho12_s))*100
  rho13_SB = (abs(rho13_mean - parameteters$corr.mat[1,3])/sd(rho13_s))*100
  rho14_SB = (abs(rho14_mean - parameteters$corr.mat[1,4])/sd(rho14_s))*100
  rho15_SB = (abs(rho15_mean - parameteters$corr.mat[1,5])/sd(rho15_s))*100
  rho16_SB = (abs(rho16_mean - parameteters$corr.mat[1,6])/sd(rho16_s))*100
  rho23_SB = (abs(rho23_mean - parameteters$corr.mat[2,3])/sd(rho23_s))*100
  rho24_SB = (abs(rho24_mean - parameteters$corr.mat[2,4])/sd(rho24_s))*100
  rho25_SB = (abs(rho25_mean - parameteters$corr.mat[2,5])/sd(rho25_s))*100
  rho26_SB = (abs(rho26_mean - parameteters$corr.mat[2,6])/sd(rho26_s))*100
  rho34_SB = (abs(rho34_mean - parameteters$corr.mat[3,4])/sd(rho34_s))*100
  rho35_SB = (abs(rho35_mean - parameteters$corr.mat[3,5])/sd(rho35_s))*100
  rho36_SB = (abs(rho36_mean - parameteters$corr.mat[3,6])/sd(rho36_s))*100
  rho45_SB = (abs(rho45_mean - parameteters$corr.mat[4,5])/sd(rho45_s))*100
  rho46_SB = (abs(rho46_mean - parameteters$corr.mat[4,6])/sd(rho46_s))*100
  rho56_SB = (abs(rho56_mean - parameteters$corr.mat[5,6])/sd(rho56_s))*100
  SB_result = list(lambda1 = lambda1_SB, lambda2 = lambda2_SB, p1 = p1_SB, p2 = p2_SB,
                   t1 = t1_SB, t2 = t2_SB,
                   rho12 = rho12_SB, rho13 = rho13_SB, rho14 = rho14_SB, 
                   rho15 = rho15_SB, rho16 = rho16_SB, rho23 = rho23_SB,
                   rho24 = rho24_SB, rho25 = rho25_SB, rho26 = rho26_SB,
                   rho34 = rho34_SB, rho35 = rho35_SB, rho36 = rho36_SB,
                   rho45 = rho45_SB, rho46 = rho46_SB, rho56 = rho56_SB)
  
  # Calculate RMSE
  lambda1_RMSE = sqrt(mean((lambda1_s-parameteters$lambda.vec[1])^2))
  lambda2_RMSE = sqrt(mean((lambda2_s-parameteters$lambda.vec[2])^2))
  p1_RMSE = sqrt(mean((p1_s - parameteters$prop.vec[1])^2))
  p2_RMSE = sqrt(mean((p2_s - parameteters$prop.vec[2])^2))
  t1_RMSE = sqrt(mean((c(t11_s, t21_s, t31_s) - c(unlist(parameteters$prop.list[1])))^2))
  t2_RMSE = sqrt(mean((c(t12_s, t22_s, t32_s) - c(unlist(parameteters$prop.list[2])))^2))
  rho12_RMSE = sqrt(mean((rho12_s - parameteters$corr.mat[1,2])^2))
  rho13_RMSE = sqrt(mean((rho13_s - parameteters$corr.mat[1,3])^2))
  rho14_RMSE = sqrt(mean((rho14_s - parameteters$corr.mat[1,4])^2))
  rho15_RMSE = sqrt(mean((rho15_s - parameteters$corr.mat[1,5])^2))
  rho16_RMSE = sqrt(mean((rho16_s - parameteters$corr.mat[1,6])^2))
  rho23_RMSE = sqrt(mean((rho23_s - parameteters$corr.mat[2,3])^2))
  rho24_RMSE = sqrt(mean((rho24_s - parameteters$corr.mat[2,4])^2))
  rho25_RMSE = sqrt(mean((rho25_s - parameteters$corr.mat[2,5])^2))
  rho26_RMSE = sqrt(mean((rho26_s - parameteters$corr.mat[2,6])^2))
  rho34_RMSE = sqrt(mean((rho34_s - parameteters$corr.mat[3,4])^2))
  rho35_RMSE = sqrt(mean((rho35_s - parameteters$corr.mat[3,5])^2))
  rho36_RMSE = sqrt(mean((rho36_s - parameteters$corr.mat[3,6])^2))
  rho45_RMSE = sqrt(mean((rho45_s - parameteters$corr.mat[4,5])^2))
  rho46_RMSE = sqrt(mean((rho46_s - parameteters$corr.mat[4,6])^2))
  rho56_RMSE = sqrt(mean((rho56_s - parameteters$corr.mat[5,6])^2))
  RMSE_result = list(lambda1 = lambda1_RMSE, lambda2 = lambda2_RMSE, p1 = p1_RMSE, p2 = p2_RMSE,
                   t1 = t1_RMSE, t2 = t2_RMSE,
                   rho12 = rho12_RMSE, rho13 = rho13_RMSE, rho14 = rho14_RMSE, 
                   rho15 = rho15_RMSE, rho16 = rho16_RMSE, rho23 = rho23_RMSE,
                   rho24 = rho24_RMSE, rho25 = rho25_RMSE, rho26 = rho26_RMSE,
                   rho34 = rho34_RMSE, rho35 = rho35_RMSE, rho36 = rho36_RMSE,
                   rho45 = rho45_RMSE, rho46 = rho46_RMSE, rho56 = rho56_RMSE)  
  

  final_result = list(mean_result, RB_result, SB_result, RMSE_result, CR_result)
  return(final_result)
}

result.test1 = simulation.function(para1, 100, n.sim = 1000)
```

